CommonBundle\Entity\OrderDelivery:
    type: entity
    table: order_delivery
    id: {  }
    fields:
        address:
            type: string
            nullable: false
            length: 160
            options:
                fixed: false
                default: ''
        addressComplement:
            type: string
            nullable: true
            length: 40
            options:
                fixed: false
            column: address_complement
        postalCode:
            type: string
            nullable: false
            length: 9
            options:
                fixed: false
                default: ''
            column: postal_code
        neighborhood:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
                default: ''
        city:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
                default: ''
        state:
            type: string
            nullable: false
            length: 40
            options:
                fixed: false
                default: ''
        type:
            type: string
            nullable: false
            length: 1
            options:
                fixed: true
                default: ''
        service:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
        price:
            type: float
            nullable: false
            precision: 10
            scale: 0
        trackingCode:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: tracking_code
    oneToOne:
        order:
            targetEntity: Order
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                order_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
